#ifndef CONSTANTS_H
#define CONSTANTS_H

enum FACTIONS {ARCEA, SA_WH, SHIRUDO, ENSHAW, KARELIA, DOTHA, EPHESUS_S, EPHESUS_N, HOLSTI, ORISSCA, NGURRKHA, SCARRA, MAYAYORE, W_FOREST, 
	CORDELLIA, HOFFNUNG_STATES, DAHOMEY, IMANIA, CAMBRIA, MARTIANAS, ALLEROD, WARLORD_STATES, MAX_FACTIONS };

enum FACTIONS_BREAKAWAY {GOLD_COAST, SUDFELL, MASSIN, JAYURA, MULL, UKOTKA, BAADENSAAR, HOFFNUNGIA, GOSUMO, CULTISTS, NOBREAKAWAY, MAX_BREAKAWAY };

enum REGION {WEST, NORTH, NORTH_TRIBAL, MULLIC, GHURRKAN, ALWENACHTA, EAST, ISLANDER, MAX_REGION};

enum RELIGION{NIKEA_T, NIKEA_R, LUNAR, RING, CULTIST_REFORM, CULTIST_DESERT, CULTIST_NEW, MAX_RELIGION};

enum WEAPON{ASSAULT_RIFLE, BATTLE_RIFLE, BOLT_RIFLE, SMG, H_GUN, SNIPER, MG, MAX_WEAPON};

enum CHARACTER_TYPE{SOLDIER, DIPLOMAT, AGENT, CULTIST, MAX_TYPE};

enum FOCUS{GROUND, AIR, DIPLOMACY, INTELLIGENCE, MAX_FOCUS};
#endif